# Generated by Django 2.2 on 2019-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick', '0002_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete='on_delete=models.SET_NULL,', to='rick.Category', verbose_name='文章分类'),
        ),
    ]
